@echo off
(
  echo Starting merge process...
  echo Checking out main...
  git checkout main
  echo Pulling latest main...
  git pull origin main
  echo Merging ui-display-check...
  git merge ui-display-check
  echo Pushing to origin/main...
  git push origin main
) > merge_log.txt 2>&1
